name: CI - Staging

on:
  pull_request:
    branches: ['staging']
    types: [closed]

jobs:
  run-base:
    if: ${{ github.event.pull_request.merged == true }}
    name: Staging pipeline
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/base.yml
    with:
      environment: staging
      ref: ${{ github.ref }}
    secrets: inherit
