name: CI - Staging

on:
  pull_request:
    branches: ['release/**']
    types: [closed]

jobs:
  run-base:
    if: ${{ github.event.pull_request.merged == true }}
    name: Staging pipeline
    uses: ./.github/workflows/base.yml
    with:
      environment: staging
    secrets: inherit
